<a href="https://colab.research.google.com/github/saketlakhotia17/IBM_MachineLearning/blob/main/7.%20Data%20Cleaning%20%26%20Naive%20Bayes%20Algorithm/Exp8_ML_I027(IBM).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exp 8 - Data Cleaning & Naive Bayes Algo

In [ ]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder


In [ ]:
df = pd.read_csv('data_preprocess_1.csv')
df

Region   Age   Income Online shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes

In [ ]:
x = df.iloc[:,:-1].values
x

array([['India', 49.0, 86400.0],
       ['Brazil', 32.0, 57600.0],
       ['USA', 35.0, 64800.0],
       ['Brazil', 43.0, 73200.0],
       ['USA', 45.0, nan],
       ['India', 40.0, 69600.0],
       ['Brazil', nan, 62400.0],
       ['India', 53.0, 94800.0],
       ['USA', 55.0, 99600.0],
       ['India', 42.0, 80400.0]], dtype=object)

In [ ]:
y = df.iloc[:,-1].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
#Handeling Missing Values

impu = SimpleImputer(missing_values=np.nan, strategy='mean')
impu = impu.fit(x[:,1:])
x[:,1:] = impu.transform(x[:,1:])
x

array([['India', 49.0, 86400.0],
       ['Brazil', 32.0, 57600.0],
       ['USA', 35.0, 64800.0],
       ['Brazil', 43.0, 73200.0],
       ['USA', 45.0, 76533.33333333333],
       ['India', 40.0, 69600.0],
       ['Brazil', 43.77777777777778, 62400.0],
       ['India', 53.0, 94800.0],
       ['USA', 55.0, 99600.0],
       ['India', 42.0, 80400.0]], dtype=object)

In [ ]:
#Handeling Categorical Data (Encode Categorical Data)
encoder_y = LabelEncoder()
y = encoder_y.fit_transform(y)
y



array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
z= df.iloc[:,0].values
encoder_z = LabelEncoder()
z = encoder_z.fit_transform(z)
z

array([1, 0, 2, 0, 2, 1, 0, 1, 2, 1])

In [ ]:
df.iloc[:,0] = z
df.iloc[:,1] = x[:,1]
df.iloc[:,2] = x[:,2]
df.iloc[:,-1] = y
df

Region      Age   Income  Online shopper
0       1       49    86400               0
1       0       32    57600               1
2       2       35    64800               0
3       0       43    73200               0
4       2       45  76533.3               1
5       1       40    69600               1
6       0  43.7778    62400               0
7       1       53    94800               1
8       2       55    99600               0
9       1       42    80400               1

# Conclusion:
1. All ML algorithms require uniformity in their format of Datasets for each column. If any column has category type of data then it is to be encoded using representative numbers.

2. For the given dataset, columns region and online shopper are represented/encoded to their representative numbers.

3. For the given dataset, NaN values are replaced by Mean ofcorresponding column.

# Naive Bayes Algo

In [ ]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

df = pd.read_csv('Naive_bayes_1.csv')
df

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [ ]:
#Convert categorical variable to numeric
df['Sex_cleaned']=np.where(df['Sex']=='male',0,1)
df['Embarked_cleaned']=np.where(df['Embarked']=='S',0,np.where(df['Embarked']=='C',1,np.where(df['Embarked']=='Q',2,3)))
df

PassengerId  Survived  Pclass  ... Embarked Sex_cleaned  Embarked_cleaned
0              1         0       3  ...        S           0                 0
1              2         1       1  ...        C           1                 1
2              3         1       3  ...        S           1                 0
3              4         1       1  ...        S           1                 0
4              5         0       3  ...        S           0                 0
..           ...       ...     ...  ...      ...         ...               ...
886          887         0       2  ...        S           0                 0
887          888         1       1  ...        S           1                 0
888          889         0       3  ...        S           1                 0
889          890         1       1  ...        C           0                 1
890          891         0       3  ...        Q           0                 2

[891 rows x 14 columns]

In [ ]:
#Clean dataset ith NaN values by removing that row

df = df[['Survived','Pclass','Sex_cleaned','Age','SibSp','Parch','Fare','Embarked_cleaned']].dropna(axis=0,how='any')
df

Survived  Pclass  Sex_cleaned  ...  Parch     Fare  Embarked_cleaned
0           0       3            0  ...      0   7.2500                 0
1           1       1            1  ...      0  71.2833                 1
2           1       3            1  ...      0   7.9250                 0
3           1       1            1  ...      0  53.1000                 0
4           0       3            0  ...      0   8.0500                 0
..        ...     ...          ...  ...    ...      ...               ...
885         0       3            1  ...      5  29.1250                 2
886         0       2            0  ...      0  13.0000                 0
887         1       1            1  ...      0  30.0000                 0
889         1       1            0  ...      0  30.0000                 1
890         0       3            0  ...      0   7.7500                 2

[714 rows x 8 columns]

In [ ]:
#Split Dataset
X_train,X_test= train_test_split(df,test_size = 0.5, random_state = 4)

nb=GaussianNB()
features = ['Pclass','Sex_cleaned','Age','SibSp','Parch','Fare','Embarked_cleaned']
nb.fit(X_train[features].values,X_train['Survived'])
pred = nb.predict(X_test[features])
pred


array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,

In [ ]:
test_samples = X_test.shape[0]
mislabelled=(X_test['Survived']!=pred).sum()
accuracy=100*(1-(mislabelled/test_samples))
print('Number of mislabelled points out of total {} points: {}'.format(test_samples, mislabelled))
print('Accuracy is: {}%'.format(accuracy))

Number of mislabelled points out of total 357 points: 85
Accuracy is: 76.19047619047619%


In [ ]:
#Split Dataset
X_train,X_test= train_test_split(df,test_size = 0.2, random_state = 4)

nb=GaussianNB()
features = ['Pclass','Sex_cleaned','Age','SibSp','Parch','Fare','Embarked_cleaned']
nb.fit(X_train[features].values,X_train['Survived'])
pred = nb.predict(X_test[features])
pred


array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0])

In [ ]:
test_samples = X_test.shape[0]
mislabelled=(X_test['Survived']!=pred).sum()
accuracy=100*(1-(mislabelled/test_samples))
print('Number of mislabelled points out of total {} points: {}'.format(test_samples, mislabelled))
print('Accuracy is: {}%'.format(accuracy))

Number of mislabelled points out of total 143 points: 30
Accuracy is: 79.02097902097903%


# Conclusion
1. Naive Bayes classifier is used on the dataset titanic.
2. Dataset is cleaned before applying Naive Bayes Classifier by removing rows with missing values and by converting category values to numbers.
3. Test Accuracy improves if test size is changed from 50% to 20%.